credentials:
  users:
    api_user:
      password: '123'
      roles: [super]

iproto:
  listen:
    - uri: '0.0.0.0:3301'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            iproto:
              listen:
                - uri: '0.0.0.0:3301'

app:
  file: '/opt/tarantool/init.lua'