services:
  tarantool:
    image: tarantool/tarantool:3.1.0
    ports:
      - "3301:3301"
    volumes:
      - ./config.yml:/etc/tarantool/config.yml
      - ./init.lua:/opt/tarantool/init.lua
      - tarantool_data:/var/lib/tarantool
    environment:
      TARANTOOL_USER_NAME: guest
      TT_CONFIG: /etc/tarantool/config.yml
volumes:
  tarantool_data: